name: Add label on pull request

on:
    pull_request:
        types: [opened, reopened]

permissions:
    id-token: write
    contents: write
    pull-requests: write 

jobs:
    add-label:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              
            - name: Get PR number
              id: pr_number
              run: |
                echo "${{ github.ref }}"
                echo "${{ github.head_ref}}"
                
            - name: Add label
              env:
                GH_TOKEN: ${{ github.token }}
              run: |
                source ${{ github.workspace }}/.github/scripts/shell.sh
         
                branchNamePrefix=$(echo "${{ github.head_ref }}" | cut -d "-" -f 2)
                labelName=$(getPullRequestLabelName "$branchNamePrefix")

                if [ -n "$labelName" ]; then
                    pullRequestNumber=$(echo "${{ github.ref }}" | cut -d "/" -f 3)
                    gh pr edit "$pullRequestNumber" --add-label "$labelName"
                fi
