name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        type: string

permissions:
  id-token: write
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release create ${{ inputs.version }} \
                      --target ${{ github.sha }} \
                      --title ${{ inputs.version }} \
                      --generate-notes
